--/* Count unprocessed data 

USE airbranch;
GO

SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS ICIS_DELETE FROM airbranch.dbo.ICIS_DELETE ;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS SSCP_AUDITEDENFORCEMENT FROM airbranch.dbo.SSCP_AUDITEDENFORCEMENT;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS SSCPFCEMASTER FROM airbranch.dbo.SSCPFCEMASTER;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS SSCPITEMMASTER FROM airbranch.dbo.SSCPITEMMASTER;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS APBSUPPLAMENTALDATA FROM airbranch.dbo.APBSUPPLAMENTALDATA;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS APBFACILITYINFORMATION FROM airbranch.dbo.APBFACILITYINFORMATION;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS APBHEADERDATA FROM airbranch.dbo.APBHEADERDATA;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS VW_ICIS_COMPLIANCEMONITORING FROM airbranch.dbo.VW_ICIS_COMPLIANCEMONITORING;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS VW_ICIS_CASEFILE FROM airbranch.dbo.VW_ICIS_CASEFILE;
SELECT SUM(CASE WHEN ICIS_STATUSIND <> 'P' THEN 1 ELSE 0 END) AS Unprocessed, COUNT(*) AS VW_ICIS_ENFORCEMENTACTION FROM airbranch.dbo.VW_ICIS_ENFORCEMENTACTION;

--*/
--/* Count staged records 

USE NETWORKNODEFLOW;
GO

SELECT COUNT(*) as [Unprocessed Submissions]
FROM   dbo.SubmissionStatus
WHERE  status IS NULL;

CREATE TABLE #counts
(
             table_name varchar(255)
           , row_count  int
);

EXEC sp_MSForEachTable
     @command1 = 'INSERT #counts (table_name, row_count) SELECT ''?'', COUNT(*) FROM ?';

SELECT table_name
     , row_count
FROM   #counts
WHERE  table_name NOT LIKE '%CERS_%'
ORDER BY table_name
       , row_count DESC;

DROP TABLE #counts;

--*/