USE airbranch;
GO

/* Update status indicator columns for all data

UPDATE airbranch.dbo.ICIS_DELETE SET ICIS_STATUSIND = 'U';
UPDATE airbranch.dbo.SSCP_AUDITEDENFORCEMENT SET ICIS_STATUSIND = 'U';
UPDATE airbranch.dbo.SSCPFCEMASTER SET ICIS_STATUSIND = 'U';
UPDATE airbranch.dbo.SSCPITEMMASTER SET ICIS_STATUSIND = 'U';
UPDATE airbranch.dbo.APBSUPPLAMENTALDATA SET ICIS_STATUSIND = 'U';
UPDATE airbranch.dbo.APBFACILITYINFORMATION SET ICIS_STATUSIND = 'U';
UPDATE airbranch.dbo.APBHEADERDATA SET ICIS_STATUSIND = 'U';
GO

--*/
/* Update status indicator columns for select data

UPDATE airbranch.dbo.ICIS_DELETE SET ICIS_STATUSIND = 'U' WHERE ID LIKE '%121%';
UPDATE airbranch.dbo.SSCP_AUDITEDENFORCEMENT SET ICIS_STATUSIND = 'U' WHERE STRAIRSNUMBER LIKE '%121%';
UPDATE airbranch.dbo.SSCPFCEMASTER SET ICIS_STATUSIND = 'U' WHERE STRAIRSNUMBER LIKE '%121%';
UPDATE airbranch.dbo.SSCPITEMMASTER SET ICIS_STATUSIND = 'U' WHERE STRAIRSNUMBER LIKE '%121%';
UPDATE airbranch.dbo.APBSUPPLAMENTALDATA SET ICIS_STATUSIND = 'U' WHERE STRAIRSNUMBER LIKE '%121%';
UPDATE airbranch.dbo.APBFACILITYINFORMATION SET ICIS_STATUSIND = 'U' WHERE STRAIRSNUMBER LIKE '%121%';
UPDATE airbranch.dbo.APBHEADERDATA SET ICIS_STATUSIND = 'U' WHERE STRAIRSNUMBER LIKE '%121%';
GO

--*/
/* Process ALL 

EXEC airbranch.etl.ICIS_STAGE_ALL;

--*/
/* Process insertions

EXEC airbranch.etl.ICIS_FACILITY_UPDATE;
EXEC airbranch.etl.ICIS_CMS_UPDATE;
EXEC airbranch.etl.ICIS_CM_UPDATE;
EXEC airbranch.etl.ICIS_CASEFILE_UPDATE;

--*/
/* Process deletions

EXEC airbranch.etl.ICIS_CF2CM_DELETE;
EXEC airbranch.etl.ICIS_EAMILESTONE_DELETE;
EXEC airbranch.etl.ICIS_CASEFILE_DELETE;
EXEC airbranch.etl.ICIS_CM_DELETE;
EXEC airbranch.etl.ICIS_CMS_DELETE;
EXEC airbranch.etl.ICIS_POLLUTANT_DELETE;
EXEC airbranch.etl.ICIS_AIRPROGRAM_DELETE;
EXEC airbranch.etl.ICIS_FACILITY_DELETE;

--*/
