USE airbranch;
GO

DECLARE @date datetime = DATEADD(day, -2, GETDATE());

SELECT *
FROM airbranch.dbo.ICIS_DELETE
WHERE ICIS_STATUSIND <> 'P'
  AND TRIGGERDATE > @date;

SELECT *
FROM airbranch.dbo.SSCP_AUDITEDENFORCEMENT
WHERE ICIS_STATUSIND <> 'P'
  AND DATMODIFINGDATE > @date;

SELECT *
FROM airbranch.dbo.SSCPFCEMASTER
WHERE ICIS_STATUSIND <> 'P'
  AND DATMODIFINGDATE > @date;

SELECT *
FROM airbranch.dbo.SSCPITEMMASTER
WHERE ICIS_STATUSIND <> 'P'
  AND DATMODIFINGDATE > @date;

SELECT *
FROM airbranch.dbo.APBSUPPLAMENTALDATA
WHERE ICIS_STATUSIND <> 'P'
  AND DATMODIFINGDATE > @date;

SELECT *
FROM airbranch.dbo.APBFACILITYINFORMATION
WHERE ICIS_STATUSIND <> 'P'
  AND DATMODIFINGDATE > @date;

SELECT *
FROM airbranch.dbo.APBHEADERDATA
WHERE ICIS_STATUSIND <> 'P'
  AND DATMODIFINGDATE > @date;

